### ISSUE TITLE
UnknownException when defining variables with dot (.)

### ISSUE THREAD

**Issue by atilag** [beltoforion/muparserx#97] opened 2019-10-31 11:10 UTC
I'm getting an exception if I define a variable with a dot into it:
```c++
ParserX parser;
Value pi(M_PI);
parser.DefineVar("np.pi", Variable(&pi)); // <--- Throws
```
Is this expected?
As a last resort I could filter them and remove the dots

Thanks for sharing this library! It's being very helpful! :)

**Comment by beltoforion** [comment] 2019-11-04 09:10
Variable, constant or function names with a "." are not allowed. As far as i can see you should receive a ParserException that explains this. This is normal behavior, just catch and evaluate the exception..

You can try to add the "." to line 62 of mpParser.cpp or call the fuinction DefineNameChars directly. This will make it an allowed character although i cannot guarantee it won't collide with other operators.

**Comment by jarom-nelson** [comment] 2020-04-09 18:54
We've been able to get this to work by building up a string of acceptable name characters, including '.', and assigning it via ParserXBase::DefineNameChars

**Comment by beltoforion** [comment] 2020-04-13 10:39
closed; not a bug; can be adjusted with existing API

**Closed by beltoforion** 2020-04-13 10:39 UTC
Labels: question
