### ISSUE TITLE
gcc makefile obj and bin directories

### ISSUE THREAD

**Issue by jeffreyscottgraham** [beltoforion/muparserx#48] opened 2015-03-26 14:54 UTC
The compile fails because the two directories 'obj' and 'bin' are assumed to exist

**Comment by jeffreyscottgraham** [comment] 2015-03-26 15:09
Here is a patch (it also sets CC and CFLAGS only if not already set, since some of us do not use clang)

--- Makefile
+++ Makefile
@@ -1,8 +1,8 @@
 #CC	=	g++
 #CFLAGS	=	-O3 -Wall -pedantic -ffast-math -fomit-frame-pointer 
 
-#CC      = clang++
-#CFLAGS	=	`llvm-config --ldflags` -O3 -Wall -pedantic
+CC      ?= clang++
+CFLAGS	?=	`llvm-config --ldflags` -O3 -Wall -pedantic
 
 # debug version
 #CFLAGS  = -Wall -ggdb  
@@ -29,7 +29,7 @@
 PATH_SAMPLE = ./sample
 
 
-all:	example
+all:	$(PATH_OBJ) $(PATH_BIN) example
 
 new:  clean example
 
@@ -76,3 +76,7 @@
 new:	
 	$(MAKE) clean
 	$(MAKE) all
+
+$(PATH_OBJ) $(PATH_BIN):
+	mkdir -p $@
+

**Comment by nasailja** [comment] 2015-04-06 18:23
+1, I had to create bin and obj and use CC=c++ as clang++ didn't exist.  I also had to add -std=c++11 to CFLAGS as GCC warned: ./sample/example.cpp:360:120: warning: ISO C++98 does not support the '%lf' gnu_printf format

**Comment by beltoforion** [comment] 2015-06-29 20:29
The issue is now fixed in the current head revision

**Closed** 2015-06-29 20:30 UTC
